package:
    name: pyamgx
    version: 0.1

source:
    git_rev: 78cb277ba83f9a98b0e7633549c9df03f1392d38
    git_url: https://github.com/shwina/pyamgx

requirements:
    build:
        - python {{ python }}
        - setuptools
        - numpy
        - cython
        - amgx
    run:
        - python
        - numpy
        - scipy
        - cudatoolkit=8.0
        - amgx
